steps:
  - id: get-secret-env
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud secrets versions access latest --secret=$_SECRET --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/.env.yaml",
      ]
  - id: cf-deploy
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - cf-validacion-proforma
      - --project=${_PROJECT_ID}
      - --source=https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/moveable-aliases/${BRANCH_NAME}/paths/src/
      - --runtime=python39
      - --entry-point=validacionProforma
      - --trigger-bucket=${_BUCKET}
      - --allow-unauthenticated
      - --env-vars-file=.env.yaml

timeout: "1800s"
