version: '3'
services:
  cf-python:
    build: .
    env_file: .env
    container_name: cf-validacion-proforma
    command: "functions-framework --source src/main.py --target=validacionProforma --signature-type=event --debug"
    volumes:
      - ./src:/app/src
    ports:
      - "${DOCKER_PORT}:8080"

  postgres:
    image: postgres:latest
    container_name: database_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proformas
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d # init scripts
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
